### ISSUE TITLE
User Review Checklist

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/draft-guide-cloud-azure#10]
@justeenr
User Review:

Allow a person with a fresh mind to read the guide and execute the steps described in the guide, test whether each step is clear enough to understand, and no logic errors.

Review and walkthrough by a non-SME or a new user with a critical and fresh pair of eyes:

- [ ] Record the time it takes to go through the entire guide
- [ ] Test each step in the guide is clear and easy to understand
- [ ] Ensure no logic errors
- [ ] Resolve anything that does not work
- [ ] Resolve anything usability issues (confusing or hard to follow)
- [ ] Achieve basic understanding/working knowledge of the topic in the guide
