### ISSUE TITLE
Post-Publishing Tests Checklist

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-cloud-azure#17]
Post-Publishing Tests

- [ ] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
- [ ] Clone repo and test finish directory with no error

Other post-publishing tasks (to be done by the Admin Team)
- [ ] Add description for the repo with link to guide's published website
- [ ] Double check the SEO title and description are added for the guide
- [ ] Create the Home and Branches wiki pages
- [ ] Ensure automated test for PR and Continuous Tests are enabled for both `master` and `qa` branches and are run on Travis, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
- [ ] Ensure the automated tests are running successfully for the daily builds
- [ ] Ensure the automated tests are running successfully for the daily docker image, if the guide uses a docker image
- [ ] Enable pull creation notification on the repo for `was-lib-guides-alerts`, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#subscribing-static-guides-repositories-to-a-slack-channel)
- [ ] Enable `master` and `qa` branches lock down, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
    -  make sure the Branch protection rules were created
- [ ] Add the new guide's repo to the `OpenLiberty/guides-common` ZenHub board
- [ ] Delete `dev` branch
- [ ] (Optional) Send announcement to slack channel(s)
- [ ] Arrange a demo at the EOI meeting
