### ISSUE TITLE
Peer review and testing checklist

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-cloud-azure#3]
Peer Review: review to be done by a peer member. 

- [x] Check that the guide has working instruction and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [x] Ensure that the automation tests are able to run with continuous daily builds

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
- Table of contents 
- Headings
- Paragraphs
- code snippets
- outputs
- links
- hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by evelinec** [comment]
@NimG98 can you do the following. I think it makes sense for you to do them. Thanks.
- [ ] Run Acrolinx Checker on draft (above 70 score approximately)
- [ ] Consider SEO title and description for the guides 
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [ ] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run with continuous daily builds

**Comment by evelinec** [comment]
Talked to @NimG98, she will do the testing on Windows platform as she has the laptop. Thanks.

**Comment by evelinec** [comment]
Tested on Linux with `centralus` location and it's working.

**Comment by NimG98** [comment]
Tested on Windows successfully, with `centralus` location.

**Comment by NimG98** [comment]
@evelinec I changed the titles and descriptions for the guide and SEO to include "Microsoft" instead of being just "Azure", it's now "Microsoft Azure". Can you look at the changes to see if it's okay?

**Comment by evelinec** [comment]
Verified one successful run of the daily build test for this draft guide. Verified the SEO changes. Looks good. Completed and closed.
